

USE ticket_webapp;


DROP TABLE IF EXISTS BugVersionAssociation;
DROP TABLE IF EXISTS Bug;
DROP TABLE IF EXISTS Severity;
DROP TABLE IF EXISTS Evolution;
DROP TABLE IF EXISTS HistoryStatut;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS TicketAssociation;
DROP TABLE IF EXISTS Ticket;
DROP TABLE IF EXISTS Statut;
DROP TABLE IF EXISTS Version;
DROP TABLE IF EXISTS Project;
DROP TABLE IF EXISTS Employee;


